/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeusTreinosRouteImport } from './routes/_authenticated/meus-treinos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminParametrosRouteImport } from './routes/_authenticated/admin/parametros'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedMinhasSessoesIndexRouteImport } from './routes/_authenticated/minhas-sessoes/index'
import { Route as AuthenticatedMinhasSessoesIdRouteImport } from './routes/_authenticated/minhas-sessoes/$id'
import { Route as AuthenticatedSessoesIndexRouteImport } from './routes/_authenticated/sessoes/index'
import { Route as AuthenticatedSessoesNovaRouteImport } from './routes/_authenticated/sessoes/nova'
import { Route as AuthenticatedTreinadorIndexRouteImport } from './routes/_authenticated/treinador/index'
import { Route as AuthenticatedTreinadorEnviarTreinoRouteImport } from './routes/_authenticated/treinador/enviar-treino'
import { Route as AuthenticatedTreinosIndexRouteImport } from './routes/_authenticated/treinos/index'
import { Route as AuthenticatedTreinosNovoRouteImport } from './routes/_authenticated/treinos/novo'
import { Route as AuthenticatedSessoesIdExecutarRouteImport } from './routes/_authenticated/sessoes/$id/executar'
import { Route as AuthenticatedSessoesIdResultadoRouteImport } from './routes/_authenticated/sessoes/$id/resultado'
import { Route as AuthenticatedTreinadorAlunosIndexRouteImport } from './routes/_authenticated/treinador/alunos/index'
import { Route as AuthenticatedTreinadorAlunosIdRouteImport } from './routes/_authenticated/treinador/alunos/$id'
import { Route as AuthenticatedTreinosIdIndexRouteImport } from './routes/_authenticated/treinos/$id/index'
import { Route as AuthenticatedTreinosIdAnaliseRouteImport } from './routes/_authenticated/treinos/$id/analise'
import { Route as AuthenticatedTreinosIdEditarRouteImport } from './routes/_authenticated/treinos/$id/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusTreinosRoute =
  AuthenticatedMeusTreinosRouteImport.update({
    id: '/meus-treinos',
    path: '/meus-treinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminParametrosRoute =
  AuthenticatedAdminParametrosRouteImport.update({
    id: '/admin/parametros',
    path: '/admin/parametros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasSessoesIndexRoute =
  AuthenticatedMinhasSessoesIndexRouteImport.update({
    id: '/minhas-sessoes/',
    path: '/minhas-sessoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasSessoesIdRoute =
  AuthenticatedMinhasSessoesIdRouteImport.update({
    id: '/minhas-sessoes/$id',
    path: '/minhas-sessoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIndexRoute =
  AuthenticatedSessoesIndexRouteImport.update({
    id: '/sessoes/',
    path: '/sessoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesNovaRoute =
  AuthenticatedSessoesNovaRouteImport.update({
    id: '/sessoes/nova',
    path: '/sessoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinadorIndexRoute =
  AuthenticatedTreinadorIndexRouteImport.update({
    id: '/treinador/',
    path: '/treinador/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinadorEnviarTreinoRoute =
  AuthenticatedTreinadorEnviarTreinoRouteImport.update({
    id: '/treinador/enviar-treino',
    path: '/treinador/enviar-treino',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinosIndexRoute =
  AuthenticatedTreinosIndexRouteImport.update({
    id: '/treinos/',
    path: '/treinos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinosNovoRoute =
  AuthenticatedTreinosNovoRouteImport.update({
    id: '/treinos/novo',
    path: '/treinos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIdExecutarRoute =
  AuthenticatedSessoesIdExecutarRouteImport.update({
    id: '/sessoes/$id/executar',
    path: '/sessoes/$id/executar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessoesIdResultadoRoute =
  AuthenticatedSessoesIdResultadoRouteImport.update({
    id: '/sessoes/$id/resultado',
    path: '/sessoes/$id/resultado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinadorAlunosIndexRoute =
  AuthenticatedTreinadorAlunosIndexRouteImport.update({
    id: '/treinador/alunos/',
    path: '/treinador/alunos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinadorAlunosIdRoute =
  AuthenticatedTreinadorAlunosIdRouteImport.update({
    id: '/treinador/alunos/$id',
    path: '/treinador/alunos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinosIdIndexRoute =
  AuthenticatedTreinosIdIndexRouteImport.update({
    id: '/treinos/$id/',
    path: '/treinos/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinosIdAnaliseRoute =
  AuthenticatedTreinosIdAnaliseRouteImport.update({
    id: '/treinos/$id/analise',
    path: '/treinos/$id/analise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinosIdEditarRoute =
  AuthenticatedTreinosIdEditarRouteImport.update({
    id: '/treinos/$id/editar',
    path: '/treinos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/minhas-sessoes/$id': typeof AuthenticatedMinhasSessoesIdRoute
  '/sessoes/nova': typeof AuthenticatedSessoesNovaRoute
  '/treinador/enviar-treino': typeof AuthenticatedTreinadorEnviarTreinoRoute
  '/treinos/novo': typeof AuthenticatedTreinosNovoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/minhas-sessoes/': typeof AuthenticatedMinhasSessoesIndexRoute
  '/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/treinador/': typeof AuthenticatedTreinadorIndexRoute
  '/treinos/': typeof AuthenticatedTreinosIndexRoute
  '/sessoes/$id/executar': typeof AuthenticatedSessoesIdExecutarRoute
  '/sessoes/$id/resultado': typeof AuthenticatedSessoesIdResultadoRoute
  '/treinador/alunos/$id': typeof AuthenticatedTreinadorAlunosIdRoute
  '/treinos/$id/analise': typeof AuthenticatedTreinosIdAnaliseRoute
  '/treinos/$id/editar': typeof AuthenticatedTreinosIdEditarRoute
  '/treinador/alunos/': typeof AuthenticatedTreinadorAlunosIndexRoute
  '/treinos/$id/': typeof AuthenticatedTreinosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/minhas-sessoes/$id': typeof AuthenticatedMinhasSessoesIdRoute
  '/sessoes/nova': typeof AuthenticatedSessoesNovaRoute
  '/treinador/enviar-treino': typeof AuthenticatedTreinadorEnviarTreinoRoute
  '/treinos/novo': typeof AuthenticatedTreinosNovoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/minhas-sessoes': typeof AuthenticatedMinhasSessoesIndexRoute
  '/sessoes': typeof AuthenticatedSessoesIndexRoute
  '/treinador': typeof AuthenticatedTreinadorIndexRoute
  '/treinos': typeof AuthenticatedTreinosIndexRoute
  '/sessoes/$id/executar': typeof AuthenticatedSessoesIdExecutarRoute
  '/sessoes/$id/resultado': typeof AuthenticatedSessoesIdResultadoRoute
  '/treinador/alunos/$id': typeof AuthenticatedTreinadorAlunosIdRoute
  '/treinos/$id/analise': typeof AuthenticatedTreinosIdAnaliseRoute
  '/treinos/$id/editar': typeof AuthenticatedTreinosIdEditarRoute
  '/treinador/alunos': typeof AuthenticatedTreinadorAlunosIndexRoute
  '/treinos/$id': typeof AuthenticatedTreinosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/_authenticated/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/minhas-sessoes/$id': typeof AuthenticatedMinhasSessoesIdRoute
  '/_authenticated/sessoes/nova': typeof AuthenticatedSessoesNovaRoute
  '/_authenticated/treinador/enviar-treino': typeof AuthenticatedTreinadorEnviarTreinoRoute
  '/_authenticated/treinos/novo': typeof AuthenticatedTreinosNovoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/minhas-sessoes/': typeof AuthenticatedMinhasSessoesIndexRoute
  '/_authenticated/sessoes/': typeof AuthenticatedSessoesIndexRoute
  '/_authenticated/treinador/': typeof AuthenticatedTreinadorIndexRoute
  '/_authenticated/treinos/': typeof AuthenticatedTreinosIndexRoute
  '/_authenticated/sessoes/$id/executar': typeof AuthenticatedSessoesIdExecutarRoute
  '/_authenticated/sessoes/$id/resultado': typeof AuthenticatedSessoesIdResultadoRoute
  '/_authenticated/treinador/alunos/$id': typeof AuthenticatedTreinadorAlunosIdRoute
  '/_authenticated/treinos/$id/analise': typeof AuthenticatedTreinosIdAnaliseRoute
  '/_authenticated/treinos/$id/editar': typeof AuthenticatedTreinosIdEditarRoute
  '/_authenticated/treinador/alunos/': typeof AuthenticatedTreinadorAlunosIndexRoute
  '/_authenticated/treinos/$id/': typeof AuthenticatedTreinosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meus-treinos'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/minhas-sessoes/$id'
    | '/sessoes/nova'
    | '/treinador/enviar-treino'
    | '/treinos/novo'
    | '/admin/'
    | '/minhas-sessoes/'
    | '/sessoes/'
    | '/treinador/'
    | '/treinos/'
    | '/sessoes/$id/executar'
    | '/sessoes/$id/resultado'
    | '/treinador/alunos/$id'
    | '/treinos/$id/analise'
    | '/treinos/$id/editar'
    | '/treinador/alunos/'
    | '/treinos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meus-treinos'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/minhas-sessoes/$id'
    | '/sessoes/nova'
    | '/treinador/enviar-treino'
    | '/treinos/novo'
    | '/admin'
    | '/minhas-sessoes'
    | '/sessoes'
    | '/treinador'
    | '/treinos'
    | '/sessoes/$id/executar'
    | '/sessoes/$id/resultado'
    | '/treinador/alunos/$id'
    | '/treinos/$id/analise'
    | '/treinos/$id/editar'
    | '/treinador/alunos'
    | '/treinos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/meus-treinos'
    | '/_authenticated/admin/parametros'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/minhas-sessoes/$id'
    | '/_authenticated/sessoes/nova'
    | '/_authenticated/treinador/enviar-treino'
    | '/_authenticated/treinos/novo'
    | '/_authenticated/admin/'
    | '/_authenticated/minhas-sessoes/'
    | '/_authenticated/sessoes/'
    | '/_authenticated/treinador/'
    | '/_authenticated/treinos/'
    | '/_authenticated/sessoes/$id/executar'
    | '/_authenticated/sessoes/$id/resultado'
    | '/_authenticated/treinador/alunos/$id'
    | '/_authenticated/treinos/$id/analise'
    | '/_authenticated/treinos/$id/editar'
    | '/_authenticated/treinador/alunos/'
    | '/_authenticated/treinos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-treinos': {
      id: '/_authenticated/meus-treinos'
      path: '/meus-treinos'
      fullPath: '/meus-treinos'
      preLoaderRoute: typeof AuthenticatedMeusTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parametros': {
      id: '/_authenticated/admin/parametros'
      path: '/admin/parametros'
      fullPath: '/admin/parametros'
      preLoaderRoute: typeof AuthenticatedAdminParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-sessoes/': {
      id: '/_authenticated/minhas-sessoes/'
      path: '/minhas-sessoes'
      fullPath: '/minhas-sessoes/'
      preLoaderRoute: typeof AuthenticatedMinhasSessoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-sessoes/$id': {
      id: '/_authenticated/minhas-sessoes/$id'
      path: '/minhas-sessoes/$id'
      fullPath: '/minhas-sessoes/$id'
      preLoaderRoute: typeof AuthenticatedMinhasSessoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/': {
      id: '/_authenticated/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof AuthenticatedSessoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/nova': {
      id: '/_authenticated/sessoes/nova'
      path: '/sessoes/nova'
      fullPath: '/sessoes/nova'
      preLoaderRoute: typeof AuthenticatedSessoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinador/': {
      id: '/_authenticated/treinador/'
      path: '/treinador'
      fullPath: '/treinador/'
      preLoaderRoute: typeof AuthenticatedTreinadorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinador/enviar-treino': {
      id: '/_authenticated/treinador/enviar-treino'
      path: '/treinador/enviar-treino'
      fullPath: '/treinador/enviar-treino'
      preLoaderRoute: typeof AuthenticatedTreinadorEnviarTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/': {
      id: '/_authenticated/treinos/'
      path: '/treinos'
      fullPath: '/treinos/'
      preLoaderRoute: typeof AuthenticatedTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/novo': {
      id: '/_authenticated/treinos/novo'
      path: '/treinos/novo'
      fullPath: '/treinos/novo'
      preLoaderRoute: typeof AuthenticatedTreinosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/$id/executar': {
      id: '/_authenticated/sessoes/$id/executar'
      path: '/sessoes/$id/executar'
      fullPath: '/sessoes/$id/executar'
      preLoaderRoute: typeof AuthenticatedSessoesIdExecutarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes/$id/resultado': {
      id: '/_authenticated/sessoes/$id/resultado'
      path: '/sessoes/$id/resultado'
      fullPath: '/sessoes/$id/resultado'
      preLoaderRoute: typeof AuthenticatedSessoesIdResultadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinador/alunos/': {
      id: '/_authenticated/treinador/alunos/'
      path: '/treinador/alunos'
      fullPath: '/treinador/alunos/'
      preLoaderRoute: typeof AuthenticatedTreinadorAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinador/alunos/$id': {
      id: '/_authenticated/treinador/alunos/$id'
      path: '/treinador/alunos/$id'
      fullPath: '/treinador/alunos/$id'
      preLoaderRoute: typeof AuthenticatedTreinadorAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/$id/': {
      id: '/_authenticated/treinos/$id/'
      path: '/treinos/$id'
      fullPath: '/treinos/$id/'
      preLoaderRoute: typeof AuthenticatedTreinosIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/$id/analise': {
      id: '/_authenticated/treinos/$id/analise'
      path: '/treinos/$id/analise'
      fullPath: '/treinos/$id/analise'
      preLoaderRoute: typeof AuthenticatedTreinosIdAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos/$id/editar': {
      id: '/_authenticated/treinos/$id/editar'
      path: '/treinos/$id/editar'
      fullPath: '/treinos/$id/editar'
      preLoaderRoute: typeof AuthenticatedTreinosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeusTreinosRoute: typeof AuthenticatedMeusTreinosRoute
  AuthenticatedAdminParametrosRoute: typeof AuthenticatedAdminParametrosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedMinhasSessoesIdRoute: typeof AuthenticatedMinhasSessoesIdRoute
  AuthenticatedSessoesNovaRoute: typeof AuthenticatedSessoesNovaRoute
  AuthenticatedTreinadorEnviarTreinoRoute: typeof AuthenticatedTreinadorEnviarTreinoRoute
  AuthenticatedTreinosNovoRoute: typeof AuthenticatedTreinosNovoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMinhasSessoesIndexRoute: typeof AuthenticatedMinhasSessoesIndexRoute
  AuthenticatedSessoesIndexRoute: typeof AuthenticatedSessoesIndexRoute
  AuthenticatedTreinadorIndexRoute: typeof AuthenticatedTreinadorIndexRoute
  AuthenticatedTreinosIndexRoute: typeof AuthenticatedTreinosIndexRoute
  AuthenticatedSessoesIdExecutarRoute: typeof AuthenticatedSessoesIdExecutarRoute
  AuthenticatedSessoesIdResultadoRoute: typeof AuthenticatedSessoesIdResultadoRoute
  AuthenticatedTreinadorAlunosIdRoute: typeof AuthenticatedTreinadorAlunosIdRoute
  AuthenticatedTreinosIdAnaliseRoute: typeof AuthenticatedTreinosIdAnaliseRoute
  AuthenticatedTreinosIdEditarRoute: typeof AuthenticatedTreinosIdEditarRoute
  AuthenticatedTreinadorAlunosIndexRoute: typeof AuthenticatedTreinadorAlunosIndexRoute
  AuthenticatedTreinosIdIndexRoute: typeof AuthenticatedTreinosIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeusTreinosRoute: AuthenticatedMeusTreinosRoute,
  AuthenticatedAdminParametrosRoute: AuthenticatedAdminParametrosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedMinhasSessoesIdRoute: AuthenticatedMinhasSessoesIdRoute,
  AuthenticatedSessoesNovaRoute: AuthenticatedSessoesNovaRoute,
  AuthenticatedTreinadorEnviarTreinoRoute:
    AuthenticatedTreinadorEnviarTreinoRoute,
  AuthenticatedTreinosNovoRoute: AuthenticatedTreinosNovoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMinhasSessoesIndexRoute: AuthenticatedMinhasSessoesIndexRoute,
  AuthenticatedSessoesIndexRoute: AuthenticatedSessoesIndexRoute,
  AuthenticatedTreinadorIndexRoute: AuthenticatedTreinadorIndexRoute,
  AuthenticatedTreinosIndexRoute: AuthenticatedTreinosIndexRoute,
  AuthenticatedSessoesIdExecutarRoute: AuthenticatedSessoesIdExecutarRoute,
  AuthenticatedSessoesIdResultadoRoute: AuthenticatedSessoesIdResultadoRoute,
  AuthenticatedTreinadorAlunosIdRoute: AuthenticatedTreinadorAlunosIdRoute,
  AuthenticatedTreinosIdAnaliseRoute: AuthenticatedTreinosIdAnaliseRoute,
  AuthenticatedTreinosIdEditarRoute: AuthenticatedTreinosIdEditarRoute,
  AuthenticatedTreinadorAlunosIndexRoute:
    AuthenticatedTreinadorAlunosIndexRoute,
  AuthenticatedTreinosIdIndexRoute: AuthenticatedTreinosIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
